export const NOTIFICATIONS = [
    {
        _id: 'DEV-000027-TESTS1',
        user_id: '651fd2b2b381a5376d301308',
        notification_code: 'EI07',
        context: {
            event: {
                name: 'Upload and featured test',
                type: 'string',
                description: 'afdaf aasd',
            },
        },
        template: {
            code: 'EI07',
            name: 'string',
            name_jp: 'string',
            email_subject: 'string',
            email_subject_jp: 'string',
            email_text: 'string',
            email_text_jp: 'string',
            email_html: 'string',
            email_html_jp: 'string',
            app_title: 'New events in your Favorites!',
            app_title_jp: '新しいイベントをお気に入りに追加しましょう！',
            app_text: '<p><span style=\"color: rgb(0, 0, 0);\">Some new events have started, check them out </span><a href=\"https://dev.ebtex.dev/en/events/{{ event.code }}\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"background-color: rgba(68, 72, 109, 0.07);\">here</a><span style=\"color: rgb(0, 0, 0);\">!</span></p>',
            app_text_jp: '<p>新しいイベントも始まりましたのでチェックしてみてください</p><p><a href=\"https://dev.ebtex.dev/en/events/{{ event.code }}\" rel=\"noopener noreferrer\" target=\"_blank\">ここ</a>！</p>',
            variables: [
                {
                    name: 'string',
                    type: 'string',
                    description: 'string',
                },
            ],
            created_at: '2023-10-12T09:39:32.702Z',
            created_by: null,
            updated_at: '2023-10-12T09:39:32.702Z',
            updated_by: null,
        },
        tags: [],
        is_persistent: false,
        is_archived: false,
        created_at: '2023-11-11T02:45:22.000Z',
    },
    {
        _id: 'DEV-000027-TESTS2',
        user_id: '651fd2b2b381a5376d301308',
        notification_code: 'email-verification',
        context: {
            name: 'email',
            type: 'string',
            description: 'The email address to be verified',
        },
        template: {
            code: 'email-verification',
            name: 'string',
            name_jp: 'string',
            email_subject: 'string',
            email_subject_jp: 'string',
            email_text: 'string',
            email_text_jp: 'string',
            email_html: 'string',
            email_html_jp: 'string',
            app_title: 'Email Verification',
            app_title_jp: 'メール認証',
            app_text: '<p>EN</p><p><br></p><p>please click this link to verify your email</p><p>https://dev.ebtex.dev/auth/email-verification?email={{email}}&amp;token={{token}}</p><p><br></p><p>The link will be expired in {{ expires_in_hours }} hours.</p>',
            app_text_jp: '<p>JP</p><p><br></p><p>please click this link to verify your email</p><p>https://dev.ebtex.dev/auth/email-verification?email={{email}}&amp;token={{token}}</p><p><br></p><p><span style=\"background-color: rgba(68, 72, 109, 0.07);\">The link will be expired in {{ expires_in_hours }} hours.</span></p>',
            variables: [
                {
                    name: 'email',
                    type: 'string',
                    description: 'The email address to be verified',
                },
                {
                    name: 'string',
                    type: 'string',
                    description: 'string',
                },
                {
                    name: 'string',
                    type: 'string',
                    description: 'string',
                },
            ],
            created_at: '2023-10-08T09:39:32.702Z',
            created_by: null,
            updated_at: '2023-10-08T09:39:32.702Z',
            updated_by: null,
        },
        tags: [],
        is_persistent: true,
        is_archived: false,
        created_at: '2023-11-20T02:45:22.000Z',
    },
    {
        _id: 'DEV-000027-TESTS3',
        user_id: '651fd2b2b381a5376d301308',
        notification_code: 'EI01',
        context: {
            event: {
                name: 'Top 1 event',
                type: 'string',
                description: 'dasagsadf afasfad qa addaf afsdaDadas asdajsdiaa asd',
            },
        },
        template: {
            code: 'EI01',
            name: 'string',
            name_jp: 'string',
            email_subject: 'string',
            email_subject_jp: 'string',
            email_text: 'string',
            email_text_jp: 'string',
            email_html: 'string',
            email_html_jp: 'string',
            app_title: 'Event ending soon!',
            app_title_jp: 'イベントもうすぐ終了！',
            app_text: '<p><span style=\"color: rgb(0, 0, 0);\">Event ({{ event.name }}) is ending soon, be sure to get those final wagers in before it’s too late!</span></p><p><span style=\"color: rgb(0, 0, 0);\">Click </span><a href=\"http://ebtex-realdev-user-707128955.ap-northeast-1.elb.amazonaws.com/en/events/{{ $event.code }}\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: rgb(0, 0, 255);\">here</a><a href=\"http://ebtex-realdev-user-707128955.ap-northeast-1.elb.amazonaws.com/en/events/{{ $event.code }}\" rel=\"noopener noreferrer\" target=\"_blank\" style=\"color: rgb(0, 0, 0);\"> </a><span style=\"color: rgb(0, 0, 0);\">to go to the event.</span></p>',
            app_text_jp: '<p>イベント ({{ even.name_jp }}) はまもなく終了します。手遅れになる前に最後の賭けをしてください!</p><p>イベントに行くには<a href=\"http://ebtex-realdev-user-707128955.ap-northeast-1.elb.amazonaws.com/en/events/{{ $event.code }}\" rel=\"noopener noreferrer\" target=\"_blank\">ここ</a>をクリックしてください。</p>',
            variables: [
                {
                    name: 'string',
                    type: 'string',
                    description: 'string',
                },
            ],
            created_at: '2023-10-12T09:39:32.702Z',
            created_by: null,
            updated_at: '2023-10-12T09:39:32.702Z',
            updated_by: null,
        },
        tags: ['urgent'],
        is_persistent: false,
        is_archived: false,
        created_at: '2023-11-21T02:45:22.000Z',
    },
];